// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// NewUserQuotaParams creates a new UserQuotaParams object
// no default values defined in spec.
func NewUserQuotaParams() UserQuotaParams {

	return UserQuotaParams{}
}

// UserQuotaParams contains all the bound params for the user quota operation
// typically these are obtained from a http.Request
//
// swagger:parameters userQuota
type UserQuotaParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: query
	*/
	UserEmail strfmt.Email
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewUserQuotaParams() beforehand.
func (o *UserQuotaParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qUserEmail, qhkUserEmail, _ := qs.GetOK("userEmail")
	if err := o.bindUserEmail(qUserEmail, qhkUserEmail, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindUserEmail binds and validates parameter UserEmail from query.
func (o *UserQuotaParams) bindUserEmail(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("userEmail", "query", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false
	if err := validate.RequiredString("userEmail", "query", raw); err != nil {
		return err
	}

	// Format: email
	value, err := formats.Parse("email", raw)
	if err != nil {
		return errors.InvalidType("userEmail", "query", "strfmt.Email", raw)
	}
	o.UserEmail = *(value.(*strfmt.Email))

	if err := o.validateUserEmail(formats); err != nil {
		return err
	}

	return nil
}

// validateUserEmail carries on validations for parameter UserEmail
func (o *UserQuotaParams) validateUserEmail(formats strfmt.Registry) error {

	if err := validate.FormatOf("userEmail", "query", "email", o.UserEmail.String(), formats); err != nil {
		return err
	}
	return nil
}
