// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// UserQuotaHandlerFunc turns a function with the right signature into a user quota handler
type UserQuotaHandlerFunc func(UserQuotaParams) middleware.Responder

// Handle executing the request and returning a response
func (fn UserQuotaHandlerFunc) Handle(params UserQuotaParams) middleware.Responder {
	return fn(params)
}

// UserQuotaHandler interface for that can handle valid user quota params
type UserQuotaHandler interface {
	Handle(UserQuotaParams) middleware.Responder
}

// NewUserQuota creates a new http.Handler for the user quota operation
func NewUserQuota(ctx *middleware.Context, handler UserQuotaHandler) *UserQuota {
	return &UserQuota{Context: ctx, Handler: handler}
}

/*UserQuota swagger:route GET /quota userQuota

UserQuota user quota API

*/
type UserQuota struct {
	Context *middleware.Context
	Handler UserQuotaHandler
}

func (o *UserQuota) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewUserQuotaParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
