// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Gestion Email Plugin",
    "title": "Gestion Email Plugin",
    "version": "1.0.0"
  },
  "basePath": "/api",
  "paths": {
    "/quota": {
      "get": {
        "operationId": "userQuota",
        "parameters": [
          {
            "type": "string",
            "format": "email",
            "name": "userEmail",
            "in": "query",
            "required": true
          },
          {
            "type": "string",
            "name": "X-API-Key",
            "in": "header",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Ok",
            "schema": {
              "$ref": "#/definitions/quota"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "error": {
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "quota": {
      "required": [
        "value",
        "limit"
      ],
      "properties": {
        "limit": {
          "type": "integer"
        },
        "value": {
          "type": "integer"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Gestion Email Plugin",
    "title": "Gestion Email Plugin",
    "version": "1.0.0"
  },
  "basePath": "/api",
  "paths": {
    "/quota": {
      "get": {
        "operationId": "userQuota",
        "parameters": [
          {
            "type": "string",
            "format": "email",
            "name": "userEmail",
            "in": "query",
            "required": true
          },
          {
            "type": "string",
            "name": "X-API-Key",
            "in": "header",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Ok",
            "schema": {
              "$ref": "#/definitions/quota"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "error": {
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "quota": {
      "required": [
        "value",
        "limit"
      ],
      "properties": {
        "limit": {
          "type": "integer",
          "minimum": 0
        },
        "value": {
          "type": "integer",
          "minimum": 0
        }
      }
    }
  }
}`))
}
